spring:
  batch:
    job:
      enabled: false
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testDb
    username:
    password:

logging:
  level:
    root: info
    com.example.batchprocessing: debug